apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
spec:
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.14.0
    helm:
      values: |
      grafana:
          adminPassword: "123456"
          resources:
            requests: { cpu: 50m,  memory: 128Mi }
            limits:   { cpu: 200m, memory: 256Mi }
      alertmanager:
          alertmanagerSpec:
            replicas: 1
            resources:
              requests: { cpu: 50m,  memory: 128Mi }
              limits:   { cpu: 200m, memory: 256Mi }
      kube-state-metrics:
          resources:
            requests: { cpu: 50m,  memory: 128Mi }
            limits:   { cpu: 200m, memory: 256Mi }
      prometheus-node-exporter:
          resources:
            requests: { cpu: 50m,  memory: 64Mi }
            limits:   { cpu: 150m, memory: 128Mi }
      prometheusOperator:
          resources:
            requests: { cpu: 50m,  memory: 128Mi }
            limits:   { cpu: 200m, memory: 256Mi }
      prometheus:
          prometheusSpec:
            retention: 3d
            walCompression: true
            scrapeInterval: 30s
            evaluationInterval: 30s
            resources:
              requests: { cpu: 300m, memory: 1Gi }
              limits:   { cpu: "1",  memory: 1.5Gi }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
