apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gsm-store
spec:
  provider:
    gcpsm:
      projectID: porfolio-480111
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: workout-gke
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
