apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-uri
  namespace: workout
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gsm-store
    kind: SecretStore
  target:
    name: mongodb-uri
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: mongodb-uri
    - secretKey: username
      remoteRef:
        key: mongodb-username
    - secretKey: password
      remoteRef:
        key: mongodb-password
