---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-uri
  namespace: workout
spec:
  encryptedData:
    MONGO_URI: AgAIxq5N5eW8GbjVVfimPEHIqjzEpQrJf9/pWIFTiJLp1jUh5APqasVyFqbBQ41uJo3QvTE8Ei52HYUpVsZ24YwkGg52iUAEh5n8i+lFvxnjJRmiBWxi9u0+58mC10w7rQWoJc1YxX6OpdrKX2mXP+0/I/h3NzGCZF6RtmAs0pvgAwwPg4TcFR/3Opckj7Ja4Mpb8TnYlLKokfpQi4CatJeNCrVv0pAvgz5XFG1W4ZRB7+2EpJAGBK2vQlmTPArV5fNnl8hW1ESVpDFGkhWjNRlijG8dSuAdiyqU92sKUo1g7Lo3ah77J7K9TJbXNaIx/mPMZMM1uHm4NgrYLdHedHhZ5CuY4fjpRqDPxX430u+dQz8CySaCrD/TnOWy7jrIuzie++S7A71XV3qrznGlElIPSxQ8cpn05Cau+FywdfgQjsjEk2WFgTLVGgQpR/8rcPJ0KVgYunPggO02M7eW3/xVVxYcnj7A1j28nh+gRIS06kS7obyVyZxw1xRafujiLFH1XY+kAXSfhkp81zapiuJk/XFY1IvaAJdp32YGcFeL19WLY6aBBKXp3emvmZcoPATzrqZymf9qCS29InqhNsh5K3LtkLE6BhYaQ3RRzNj6ElSklSlu9J+4SMhxGFzq/x0I9HsaIvUXIbHwxc+h8eE4qFtD2Vy2qpysJiv0z5xxht57eO2whnNhfQ4Z+tlIkLCaQYDa8Pxz3z3LIyOmNCVokxLocRQh1pyN+WsMi/EE9yEmromPUqvLdnK/D+zBtiOkRz/LvzU2ggGfQ0i6adAT9tojPlNh0iQ+AX5AS4IGv1m+VEOkMzy/MbWet3vWbHfCfPt7rzJikeurrWWYH+3NnsOM3tpF0nfYY/HS3HWigr5PdpT+OJaQj4fYJJCgGn0=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-uri
      namespace: workout
