---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-user-credentials
  namespace: workout
spec:
  encryptedData:
    password: AgDMHU1lf9EitiAQRzKgNh+TALDvtciWp0VRfVBOK5QXtwdMpzYDkBXUv7vxMW0t2G55lPHv73XFX84BPClv6nK20UGu4YvuLaI+VkCP1iYKH0FUGGUP+w96f3RQPpPyJZiqi3qHQK/EOgAvZNyGH6Upjf7Hxny4q362GbOsMUZu6s0mxi1QcC2MwgsqxM20iV8SVQh6M92peo6ExB+8iJNehuyEGkKi0df+dk+YKPbNQmAiFRIGO5c5VNvWCCXrhbD+Kj399SXMN+wX7/4XCo4FXzhFZoEsNm4vRkTQkDrunCMehLJ//TaXhA+ga/ESG/swQL8wI3WjZuAGJZZUiZsVvTSXVwv6eXCz2RthZtL+/IQGD1Ab3mqwYB5TCvn5TDGpWbn3VfDVcn/qnCGGyATw5GDkdg54bFFQDirebLDQvv3X8tzxYzj18r8vfO0gIa3GU1MC05EfjPMqM7KzLDPnFvUgIAcYV9ZBpPRD1eof1va/80zdxB98VavtsIA7UgH6ag6cGDz0a0WT1AmwJZe6Gp/NhQgNjloSbletjAbVbIs8Djy0LGeafvY2M86L2VlpmPRfOrDMhHD/eQd/tx7Kdx/pR8ECO+7NgQtHFsxV8Go0bFIQdbW2tnGABoMvsFvE+HCVwlKXoIgkWG8lzsWQEOpCyZS/VNcTwQKi08cqsrxEQ1EwHyAsLsKSPmYsVFqC1GzbjpqlC7SqHLBoWA==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-user-credentials
      namespace: workout
    type: Opaque
