---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-uri
  namespace: workout
spec:
  encryptedData:
    MONGO_URI: AgCyLBg3gSqlJr8yk1/6UVrO1i7OJ9bNo7VU5oe3cyfXT1M608j4zY2JI0EFXcesftfCG7bEouUEoGvZcPVtkdhCCTrhgYoxOCzy+BTDVU7Y7pY+cgJ8n3X/soicq1WDu9pHtKCuGkmjO5QRxAIcBleSVhYEILtn3Y3QkXsDLOyxdLaJPTYPveNjgzmaUX1PejCCM3uM5m8MiZtnIqlBkUs2zTI7FoEpOCIUF09ZbYkZH5pl/zaAUBG5uggs/JmaYiaFYlBBw982JlXw/M/s3gtQ1WyWnqaMJze3lWPZvjAKC08IGP47sXPBa6l8rm5JvHdZAb0ho70O9AsE5PEvk4Ir4Ry2Um8xjK53MBnMnF4hNEJwMoe//Eaxeqe+rwBxxMSadpgZr156ZtQDSUhfGr3X5tUoTjKaAtd1EGZO/I3hH6BtuAcgis59VduoZPHrb0/ZyvjWil3m4LKM1yMT8orGg0xVJIMQUBdr0CMRgdWp7LsFA3FJ0kp8GAOuBqBZcY6ujsLUyi6AckMjMAvLZ/94zwhSkK+m6d4bz+20OMvISlNdcRKbaKSA5ME/m+EP0V5fSNK/naf+xlwKSGiVyFcNIJzz77JxEHAIg3Y4zE//MMwdLHXHFa3/qq8trhXqy4gGMuogBBrUCG+6DcdBY0GTgX9gw84EiMhMVIFXavcKEH8H8ZX9yCvAFEJ/VWdzBLzH6NnTxAK/RSA7ue03IDDWrTCGASlQvjLr91q3Iq1NvuxgUm+fIduzkeaz84X7+AJ8fZkT0g+Ss6JElBvR6rKNVH7WWseixQiDyazBdLz1UYEwBmXZctKifQ72SonQk0Mb0ZE2+HNHL7TWfKY/+bSsgPKv5h8tiA==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-uri
      namespace: workout
    type: Opaque
