---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-user-credentials
  namespace: workout
spec:
  encryptedData:
    password: AgAQyUXAX0Awzo/oMHQg/0fltJJ/sYyGap2U1VNFreuOgTZB+j0x51PrPsJWW7N54vgFQ8FNxmPDxoSxowZxASNyJsTm8otkkfXv5oXp6xLH6yjaew+Ab8n0IakO5/MsKa2KMHXDwjGqg1C6+Rp9H6h58snO1LAGOqAFx6nZLd0ZuFsHLMowmLdxSP+v+n11WhBRTHnkYRP3ornEq2hU5hIxVachYgm6r6S4qURjA0cLnD0L9hnLXzRImw1yfTTsoYCUWye4MAH7qlnnVnazstbPEjDNgdvhaw5vQsUWDscu2HqxzgMOXuGrTk9i96VbyfPk374yECaKiBJqTtilG1imVM2d9Io2rE/LnvRooRzy/oJAHdLwdhWv06qgwqpNDFF2T57tsnGUS3fdJPS6t7Dj3t9gh2JuzUAB34NoAfocahtLLNgX9EtBTDm+LyeiBVOko312kNZmf5mbenRyH/WNYI/Gt2+erVKYeIcIDqbfql+e/ezgUFJekyhJ2DfHxH2GSIIK0B15WB/yqKv9HfKQlMmTdy/RPmxofWOjJFZcnTVbpdrgHTNBrxEdTdCQbSqEcwzCbpd9w/ikCDBg6xm1IQFEuJ3yfpWCjpNiiFKVZS/NKsYkDSJqWxgFypjzoTG4ohcrHAJxRyxJX72ESgBRBV5VU7zHFiPr083x4+ICVxuGWfGPatXnnCC9mTaEm3xUgYEtvAodyisFqn6KJQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-user-credentials
      namespace: workout
